name: cdnacupcake2
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cython=0.29.28
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.18
  - llvm-openmp=13.0.1
  - ncurses=6.3
  - numpy=1.22.3
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.8.5
  - python_abi=3.8
  - readline=8.1.2
  - scipy=1.8.0
  - setuptools=58.0.4
  - sqlite=3.37.2
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - biopython==1.79
    - bx-python==0.8.13
    - cupcake==28.0.0
    - joblib==1.1.0
    - pysam==0.18.0
    - scikit-learn==1.0.2
    - six==1.16.0
    - sklearn==0.0
    - threadpoolctl==3.1.0
