 name: cdnacupcake
  channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - dbus=1.13.6
  - emacs=27.2
  - expat=2.4.7
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.96
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.6
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - harfbuzz=3.4.0
  - icu=69.1
  - jbig=2.1
  - jpeg=9e
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=12.0.1
  - libdeflate=1.10
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.70.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - librsvg=2.52.5
  - libtiff=4.3.0
  - libwebp-base=1.2.2
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - ncurses=6.3
  - nettle=3.6
  - openssl=3.0.0
  - pango=1.50.5
  - pcre=8.45
  - pip=22.0.4
  - pixman=0.40.0
  - python=3.10.2
  - python_abi=3.10
  - readline=8.1
  - sqlite=3.37.0
  - tk=8.6.12
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - cython==0.29.28
    - numpy==1.22.3
    - scipy==1.8.0
    - setuptools==60.9.3
