# From here: https://github.com/reviewdog/action-misspell
name: reviewdog misspell
on: [push]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout
      - name: misspell
        uses: reviewdog/action-misspell@master
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          reporter: github-pr-review
          level: error